import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';

import { registerDebugTools } from './debug.js';
import { registerCommandTools, registerPatternSearchTool } from './command.js';
import { registerRegisterTools } from './registers.js';
import { registerMemoryTools } from './memory.js';
import { registerDisassemblyTools } from './disassembly.js';
import { registerBreakpointTools } from './breakpoints.js';
import { registerSymbolTools } from './symbols.js';
import { registerStackTools } from './stack.js';
import { registerThreadTools } from './threads.js';
import { registerModuleTools } from './modules.js';
import { registerSearchTools } from './search.js';
import { registerAnalysisTools, registerDatabaseTools, registerAddressConvertTools, registerWatchdogTool, registerCompoundAnalysisTool, registerEventSubscriptionTool } from './analysis.js';
import { registerTracingTools } from './tracing.js';
import { registerDumpingTools } from './dumping.js';
import { registerAntidebugTools } from './antidebug.js';
import { registerExceptionTools } from './exceptions.js';
import { registerProcessTools, registerHandleTools, registerControlFlowTools, registerPatchTools } from './process.js';
import { registerAdvancedDumpTools } from './advanced_dump.js';
import { registerContextTools, registerFunctionTools, registerScriptTools, registerSystemTools, registerAssemblerTools, registerBookmarkTools, registerSnapshotDiffTools, registerAutoPatchTools, registerBatchAnnotationTools } from './context.js';
import { registerFridaBridgeTools } from './frida_bridge.js';

export function registerAllTools(server: McpServer) {
  registerDebugTools(server);
  registerCommandTools(server);
  registerRegisterTools(server);
  registerMemoryTools(server);
  registerDisassemblyTools(server);
  registerBreakpointTools(server);
  registerSymbolTools(server);
  registerStackTools(server);
  registerThreadTools(server);
  registerModuleTools(server);
  registerSearchTools(server);
  registerAnalysisTools(server);
  registerDatabaseTools(server);
  registerAddressConvertTools(server);
  registerWatchdogTool(server);
  registerCompoundAnalysisTool(server);
  registerEventSubscriptionTool(server);
  registerTracingTools(server);
  registerDumpingTools(server);
  registerAntidebugTools(server);
  registerExceptionTools(server);
  registerProcessTools(server);
  registerHandleTools(server);
  registerControlFlowTools(server);
  registerPatchTools(server);
  registerAdvancedDumpTools(server);
  registerContextTools(server);
  registerFunctionTools(server);
  registerScriptTools(server);
  registerSystemTools(server);
  registerAssemblerTools(server);
  registerBookmarkTools(server);
  registerSnapshotDiffTools(server);
  registerAutoPatchTools(server);
  registerBatchAnnotationTools(server);
  registerPatternSearchTool(server);
  registerFridaBridgeTools(server);
}